/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCheckbox: typeof import('element-plus/es')['ElCheckbox']
    ElCheckboxGroup: typeof import('element-plus/es')['ElCheckboxGroup']
    ElCol: typeof import('element-plus/es')['ElCol']
    ElDatePicker: typeof import('element-plus/es')['ElDatePicker']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElRadio: typeof import('element-plus/es')['ElRadio']
    ElRadioGroup: typeof import('element-plus/es')['ElRadioGroup']
    ElSegmented: typeof import('element-plus/es')['ElSegmented']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    ElSelectV2: typeof import('element-plus/es')['ElSelectV2']
    ElSwitch: typeof import('element-plus/es')['ElSwitch']
    ElTimePicker: typeof import('element-plus/es')['ElTimePicker']
    ElTimeSelect: typeof import('element-plus/es')['ElTimeSelect']
    FieldCheckbox: typeof import('./src/components/fields/FieldCheckbox.vue')['default']
    FieldCheckboxGroup: typeof import('./src/components/fields/FieldCheckboxGroup.vue')['default']
    FieldCol: typeof import('./src/components/FieldCol.vue')['default']
    FieldDatePicker: typeof import('./src/components/fields/FieldDatePicker.vue')['default']
    FieldInput: typeof import('./src/components/fields/FieldInput.vue')['default']
    FieldItem: typeof import('./src/components/FieldItem.vue')['default']
    FieldRadioGroup: typeof import('./src/components/fields/FieldRadioGroup.vue')['default']
    FieldSelect: typeof import('./src/components/fields/FieldSelect.vue')['default']
    FieldSpan: typeof import('./src/components/fields/FieldSpan.vue')['default']
    FieldSwitch: typeof import('./src/components/fields/FieldSwitch.vue')['default']
    FieldTimePicker: typeof import('./src/components/fields/FieldTimePicker.vue')['default']
    FieldTimeSelect: typeof import('./src/components/fields/FieldTimeSelect.vue')['default']
    FormBuilder: typeof import('./src/components/FormBuilder.vue')['default']
    ShowIfWrapper: typeof import('./src/components/ShowIfWrapper.vue')['default']
  }
}
